### ISSUE TITLE
snap is creating logins credentials in the snap instead of home directory

### ISSUE THREAD

**Issue by tbille** [canonical/greenhouse-automations#43]
The snap is currently creating the credential files in the snap instead of your home directory.

The expected behaviour is to have the credentials in your home directory.

**Comment by goulinkh** [comment]
As the file remains after a snap update, there is no need to put the file to the user folder, it's fine to keep it in the snap's user home folder.

**Comment by tbille** [comment]
After investigation it seems the issue came from the cookie being out of date.
Closing the issue.
