### ISSUE TITLE
Tick Indeed and remote when job posting

### ISSUE THREAD

**Issue by tbille** [canonical/greenhouse-automations#66]
![image](https://user-images.githubusercontent.com/2707508/155743490-a53a271c-d90d-471a-941c-55b7930f963c.png)

**Comment by ihetu** [comment]
Add the location the job post is anchored to to the location text post. The location will match with the one mentioned in the Post Details section. (e.g. Home based - Europe, Amsterdam will be posted to Amsterdam)
